### ISSUE TITLE
Wrong line end characters

### ISSUE THREAD

**Issue by deathaxe** [btrekkie/WrapAsYouType#1]
Altering text which is written back to a `View` does not require special line ending handling.

The result of adding `\r\n` to a view is displayed here:

![grafik](https://user-images.githubusercontent.com/16542113/48970680-89179580-f00f-11e8-94bf-cc55783e409e.png)

A python plugin can safely use `\n` to add a line break on all OSs without respect of ST's line endings setting. This setting is used by ST to decide which line ending to write to the file while saving.

Hence the `_line_break()` method can be simplified:

https://github.com/btrekkie/WrapAsYouType/blob/8ada4261174a9967c2ac4c315376f62cdbd058e6/wrap_fixer.py#L602

**Comment by btrekkie** [comment]
Thanks!  I didn't know that.
