### ISSUE TITLE
Non-breaking spaces are neither honored nor preserved

### ISSUE THREAD

**Issue by HadrienG2** [btrekkie/WrapAsYouType#11]
At the moment, WrapAsYouType does not handle non-breaking spaces (unicode codepoint 0xA0) very well.

First it will gladly cut a line at their position, even though by the very definition of non-breaking spaces it should refrain from doing so and cut at the previous word boundary instead.

Second, in the process of cutting a line at this incorrect position, it will replace the non-breaking space with a line feed, which means that if the things before and after the non-breaking spaces are subsequently reflowed together through more additions and deletions, the non-breaking space will effectively have been replaced with a regular space.

To be honest, I'm not sure if this is a problem in the WrapAsYouType plugin or the core Sublime engine, as I've seen other text reflow Sublime plugins handle non-breaking spaces in similarly incorrect ways.

**Comment by btrekkie** [comment]
Thanks for reporting this! Luckily, the fix is quite simple.
