### ISSUE TITLE
Optional forward/backwards-looking word wrapping

### ISSUE THREAD

**Issue by dhelonious** [btrekkie/WrapAsYouType#5]
I really like the ability to use hard wrapping only in comment sections. However, most of the time I use formatted text for documentations and not flowing text. Therefore, I would really like to see an option to enable only forward-looking word wrapping in comments. Is this possible?

**Comment by btrekkie** [comment]
This would not be difficult to add, but before I do so, I'd like to understand the issue better, so that I can be confident this is the appropriate fix.  Is the problem that sometimes you have to manually add line breaks to keep some formatted text together, and you want to prevent WrapAsYouType from undoing those line breaks?  (In some cases, this can be addressed using the [`"wrap_as_you_type_word_regex"` setting](https://github.com/btrekkie/WrapAsYouType#wrap_as_you_type_word_regex), as annoying as that is to set up.)  Or is it a different problem?

Would you also want to disable moving text from the beginning of the next line to the end of the current line?

My one concern with only performing forward-looking word wrapping is that it will not work in a fairly common case: where the user makes a mistake in his typing and then uses the backspace key to correct it.  If the user is near the beginning of a new line, he would want to move the word he just corrected to the end of the previous line, but this requires backward-looking word wrapping.  However, if in certain use cases, the advantages of disabling backward-looking word wrapping outweigh the disadvantages, then it's worth adding as an option.

**Comment by dhelonious** [comment]
Thank you for the detailed answer. I think the `"wrap_as_you_type_word_regex" setting` could indeed be useful in the future. For one of my issues the `"wrap_as_you_type_paragraphs" setting` provided a good solution: if i want to write a TODO note, e. g. `# TODO: do something`, I don't want to join this with the previous comment text. I now use (for Python):
```json
	"wrap_as_you_type_paragraphs":
	[
		{
			"first_line_regex": "^.*TODO:.*$",
			"single_line": true
		}
	]
```
However, if you plan on removing `"wrap_as_you_type_paragraphs"`, how would I realise something like this?

Concerning the forward-wrapping: your are correct, the use of forward-looking word wrapping only is rather simple compared to the abilities of this plugin. I still think, that an option for this would be worth it. In the Readme you compare WrapAsYouType to AutoWrap. AutoWrap does only forward-looking word wrapping. However, I cannot use it in source code, because it would also wrap my code lines. With WrapAsYouType I can specify to only wrap text in comments. This is still a huge advantage in my perspective.

Another reason might be compatability with other packages, as discussed in issue #2. Of course I hope, that this issue can be fixed in some way, but the simplest way to fix this for me would be to disable backwards-looking word wrapping. As I said above, this would still be advantageous for me.

**Comment by btrekkie** [comment]
Interesting, I have a similar `"wrap_as_you_type_paragraphs"` entry myself.

So in other words, you would like to disable backward-looking word wrapping in order to make sure your explicitly added line breaks stick?  So this would be a workaround for any plugins that prevent 1e42888 from working, and for the fact that the ability of WrapAsYouType to remember explicit line breaks is inherently limited.  I can get on board with that.

Note that even if WrapAsYouType is restricted to forward-looking word wrapping, it could still mess up the line breaks.  This is because changing the middle of a paragraph can result in reflowing the rest of the paragraph.  So if you press enter, type in some text, and then go back and edit the previous paragraph, WrapAsYouType might wrap the text you just entered as part of the previous paragraph.

As you suggest, README.md mentions that I might remove the `"wrap_as_you_type_paragraphs"` setting in the future.  However, I don't intend to remove that setting without replacing it with another setting that has similar functionality.  It's more of a warning in case someone comes up with a better design for a setting that achieves the same thing.

**Comment by dhelonious** [comment]
Thank you for all the explanations. I completely forgot about the forward-looking word wrapping in the middle of a paragraph. Maybe two options, that is one for backwards-looking word wrapping and one for forward-looking word wrapping, could be used to give a better control over the behavior of WrapAsYouType. If both are disabled, I could use WrapAsYouType for pure hard word wrapping inside comments. However, since I cannot imagine a use case at the moment, where I would disable only forward-looking or backward-looking word wrapping seperately, a single option to disable both could be sufficient.

**Comment by btrekkie** [comment]
@dhelonious I'm a little unclear on how this would work.  If both forward- and backward-looking word wrapping are disabled, what sort of wrapping behavior would take place?

**Comment by dhelonious** [comment]
@btrekkie I think about only hard wrapping at a specific width, so that no modifications of any previous or following lines in the same paragraph are made. As I said, such an option would disable almost any feature of WrapAsYouType and I would have to make manual changes whenever I change text.

Forward-looking and backwards-looking word wrapping is awesome in Markdown paragraphs or any other text-based file. In source code, however, I cannot use it, because I rarely write block text. But I would really like the ability to write comments without the need to think about hard wrapping all the time. It would be awesome to let WrapAsYouType break the comment lines at a specific width without doing something else. Surely, this is my very own preference, but that's why I asked, if such an option is possible. I hope that I could make my point a little bit clearer now.

**Comment by btrekkie** [comment]
Wrapping without altering the next or previous line is not as useful as it sounds.  If you were to add to the middle of a paragraph, then every time the current line overflows, WrapAsYouType would move the last word in the current line to its own line.  Pretty soon, you'd have ten lines in a row containing one word each.  I assume that's not what you want either?

By the way, you don't need to be so concerned about convincing me.  Worst-case scenario, I can create a separate branch with your preferred behavior.

**Comment by dhelonious** [comment]
I agree, this is not very useful. I rather thought about something more simple: when my cursor reaches the defined end of the line, a line break is added and the cursor is moved to the new line. If I add text in the middle of a line the text will overlapp. But when I think about it again, this does not sound like something a plugin called WRAPasyoutype should do.

How about this: something like a "light mode" without forward/backwards-looking wrapping. The line is broken when the cursor is at the end of a line. If I add text in the middle of a line, the overlapping word will be broken and the text will flow into the new line if I keep typing. However, WrapAsYouType will only change the current line in which the cursor is and every line below, which was automatically created by text wrapping (kind of a "forwad-looking text wrapping light"). If the cursor changes to another line the history will be forgotten. If I use backspace to join the current line with the previous one, this line could again be wrapped.

Of course, in block text paragraphs I would have to do a lot of manual work. However, with source code comments in mind, I think that such a "light mode" would always do what I want to be done without messing with other comment lines. What do you think about that?

My only concern is, that, although I think this would be the behavior I wish for, it is not such a subtle change as I first thought. My intention was not, that a separate branch with completely different behavior emerges. I thought, that additional options for some more control over the existing behavior could be provided. Especially because of forward/backward-looking text wrapping I had to disable the plugin with a heavy heart, as intended linebreaks were not preserved (not only because of issues with other packages as mentioned in #2).

**Comment by btrekkie** [comment]
All right, that makes sense.

I'm not sure I agree with your assessment that the current behavior of WrapAsYouType is ill-suited to wrapping formatted code comments.  I had WrapAsYouType enabled when I was writing most of the comments for this project (e.g. the comments in wrap_fixer.py), and I thought it worked pretty well.  My comments have some degree of structure, at least when it comes to specifying the types of fields, arguments, and return values.

Still, it seems like giving the user the option for more passive wrapping behavior would be generally useful.  I'm planning to add the ability to enable the behavior you described using a `"wrap_as_you_type_passive"` setting.

**Comment by dhelonious** [comment]
First of all, thank you for your consideration. I'm looking forward to that passive setting which hopefully makes WrapAsYouType compatible with BracketHighlighter.

I did not mean to say, that the current behavior is completely ill-suited for commenting. On the contrary, its automatic wrapping abilities are awesome for ordinary comments. However, I would also like to use it for docstrings, which could also be written in one go since 1e428885ce00edc41b966b96852ce33315de14fe. On changing existing docstrings or by using snippets like those provided by DockBlockr or AutoDocstring the intended line breaks are removed. I understand that there is no way to determine which line breaks are intended and which not and at the same time to provide fully automatic text wrapping.

So thanks again for this awesome plugin and keep up the good work. WrapAsYouType is one of my favorite plugins and already helps me a lot with my comments.

**Comment by btrekkie** [comment]
WrapAsYouType can be configured to work with docblocks, by adding the following setting:

```json
{
    "wrap_as_you_type_paragraphs": [
        {
            "first_line_regex": "^@(arg|argument|param|returns?)\\s+\\S+\\s+",
            "indent_group": 0
        },
        {
            "first_line_regex": "^@([a-zA-Z]+(\\s+|$)|[a-zA-Z]*$)",
            "indent_group": 0
        }
    ]
}
```

If you include parameter names in your docblocks, then use this setting instead:

```json
{
    "wrap_as_you_type_paragraphs": [
        {
            "first_line_regex": "^@(arg|argument|param)\\s+\\S+\\s+\\S+\\s+",
            "indent_group": 0
        },
        {
            "first_line_regex": "^@returns?\\s+\\S+\\s+",
            "indent_group": 0
        },
        {
            "first_line_regex": "^@([a-zA-Z]+(\\s+|$)|[a-zA-Z]*$)",
            "indent_group": 0
        }
    ]
}
```

It's also possible to configure the `"wrap_as_you_type_paragraphs"` setting for other structured formats, such as the format used in wrap_fixer.py.  Is there a particular format that's giving you trouble?

I'm glad you like the plugin.  Thanks for your patience, and please understand that I'm asking you all of these questions in an attempt to make the user experience as good as possible.

**Comment by dhelonious** [comment]
Wow, that's interesting. I mainly use Google-style docstrings, which should work with only minor adjustments of your examples. I will test this in the weekend. However, I would suggest to add this code snippet to the long list of examples you already have in the Readme.

**Comment by btrekkie** [comment]
@dhelonious Will do.  I'll either replace the Javadoc example with a setting that works with DocBlockr / DoxyDoxygen, or add the setting as a new example.  I'll still add a `"wrap_as_you_type_passive"` option though.  It might be useful for users who are unable or unwilling to find a `"wrap_as_you_type_paragraphs"` setting that works with their formatting, or for other use cases.

Here's a first pass at a `"wrap_as_you_type_paragraphs"` setting for Google-style docstrings:

```json
{
    "wrap_as_you_type_paragraphs": [
        {
            "first_line_regex": "^(\\*?\\*?[a-zA-Z_][a-zA-Z_0-9]*|[a-zA-Z_][a-zA-Z_0-9]*\\[.+\\]|[a-zA-Z_][a-zA-Z_0-9]* \\([^\\)]+\\)): ",
            "indent": "    "
        },
        {
            "first_line_regex": "^((>>>|\\.\\.\\.)( |$)|<BLANKLINE>$)",
            "single_line": true
        },
        {
            "first_line_regex": "^(\"\"?|''?)$",
            "single_line": true
        }
    ]
}
```

The first element is for various annotations.  I tried to write it so as to minimize the chances that a colon in the middle of a sentence will be mistaken for a formatting colon, but this is definitely still possible.  The second element is for the doctest format.  The third element helps when adding a docstring to existing code; it prevents WrapAsYouType from wrapping the closing triple quote with the following line of code, as the user types the triple quote.

If you manage to work out a setting that's a little more "battle-tested," I'd like to add it as an example to README.md.

**Comment by dhelonious** [comment]
@btrekkie Once again thank you for your continued support. Your regex is far more advanced than what I had in mind, but it works perfectly fine.

The `"wrap_as_you_type_passive"` setting is perfect and finally solves the issues with BracketHighlighter!
