### ISSUE TITLE
Feature request: automatically start new comment line after pressing Enter

### ISSUE THREAD

**Issue by schrockwell** [btrekkie/WrapAsYouType#7]
When starting a new line within a comment block, it would be awesome if this plugin had a flag to automatically begin the new line with the `line_start` character and the current indentation. This would make it much nicer to break up larger blocks of text into paragraphs.

E.g. if the cursor was here (with the pipe representing the text cursor):

```
# This is a test.|
```

And Enter is pressed twice, it should become:

```
# This is a test.
# 
# |
```

Or, if the cursor is in the middle of a line:

```
# This is also a test. |Please do not be alarmed.
```

and Enter is pressed twice, it should result in:

```
# This is also a test.
#
# |Please do not be alarmed.

**Comment by btrekkie** [comment]
The [DocBlockr](https://github.com/spadgos/sublime-jsdocs) plugin has this feature, if you set the `"jsdocs_extend_double_slash"` setting to true. Does that work for you, or do you feel it should be built into WrapAsYouType?

**Comment by schrockwell** [comment]
Unfortunately DocBlockr notably does not support Ruby and a lot of other languages, whereas WrapAsYouType is much more general-purpose because it's configurable.

It would be a neat addition, but you're the author, so I understand if you think this oversteps the responsibility of the plugin.

**Comment by btrekkie** [comment]
Gotcha.

**Comment by btrekkie** [comment]
You can now enable this feature by setting the `"wrap_as_you_type_enter_extends_section"` setting to true.

This is a handy feature. I think I'll use it in my own work. :smiley:

**Comment by schrockwell** [comment]
You da man! Thanks so much.
