### ISSUE TITLE
Javascript settings didn't work for me (what worked for me is below)

### ISSUE THREAD

**Issue by natlefiyr** [btrekkie/WrapAsYouType#8]
Hi btrekkie!

I love this package, it's super helpful!!  I did notice that the Javascript settings that were recommended in the README didn't seem to work for me (I'm using Sublime Text 3).  This is what worked for me:
```
"wrap_as_you_type_sections": [
        {
            "line_start": "*", // I removed the spaces around the asterisk
            "selector": "comment.block - punctuation.definition.comment"
        },
        {
            "combining_selector":
                "source - (comment | constant | entity | invalid | keyword | punctuation | storage | string | variable)",
            "line_start": "\/\/", // I escaped the forward slashes
            "selector": "comment.line"
        }
    ],
}
```

It might be helpful to other users to call out this fix, if you confirm it?

In any case, many thanks for making this excellent package!  Game changing!
-natlefiyr

**Comment by btrekkie** [comment]
I'm glad you like it, and thanks for reporting this. What problem specifically were you having when you were using the recommended setting? I'd like to know what the text was immediately before the problem occurred, what change you made, and what the text was after the problem occurred (e.g. word wrapping didn't happen when it should have).

The additional backslashes in your setting wouldn't have any effect. In JSON, the string is intepreted as two forward slashes, whether or not there are backslashes. You can confirm this by opening a tab where the setting applies, opening the console (Ctrl+\`), and printing the setting using `sublime.active_window().active_view().settings().get('wrap_as_you_type_sections')`. Both with and without the backslashes, I see the following output:

```
[{'selector': 'comment.block - punctuation.definition.comment', 'line_start': '*'}, {'selector': 'comment.line', 'combining_selector': 'source - (comment | constant | entity | invalid | keyword | punctuation | storage | string | variable)', 'line_start': '//'}]
```

As for removing the spaces around the asterisk, are you writing comments with no indentation, like this?

```
/**
* Returns the square root of "value".
*/
function sqrt(value) {
    ...
}
```

Or perhaps comments with no space after the asterisk, like this?

```
/**
 *Returns the square root of "value".
 */
function sqrt(value) {
    ...
}
```

Personally, I write comments with at least one space before and after the asterisk, like this:

```
/**
 * Returns the square root of "value".
 */
function sqrt(value) {
    ...
}
```

I crafted the setting with the third style in mind. If you use a different style, then that would explain why my suggested setting doesn't work for you.

**Comment by natlefiyr** [comment]
Thanks for the quick response!  And sorry for taking a little bit to get back.

I tried to replicate the issues I had mentioned with the original settings values.  I wasn't able to replicate the '//' issue, I'm not sure why that seemed to be an issue before (I'm pretty sure it was though; I guess that will remain a mystery; did I not save the settings file??).  I also did the print setting command you specified and confirmed for myself that both with and without the backslashes the value is the same as you stated.

For the asterisk issue, it was true that I did not have a space after the asterisk - I had a tab after the asterisk where I was editing.

In any case, it makes sense why there was the discrepancy on the asterisk setting.  Could be worth calling out but maybe it's apparent enough to people as-is?  It didn't take me too long to fix it though I didn't fully understand why it wasn't working before.  When I had used the settings for another language it just worked when I dropped in the setting so I was surprised when this one needed some tweaking.

In any case, many thanks for your quick clarification on this, and for a wonderful plugin!

**Comment by btrekkie** [comment]
Got it. Here's what I'll do: I'll use a modified `"wrap_as_you_type_sections"` setting in my own work for a little while, and if I don't run into any problems, I'll change the recommended settings in README.md. In place of `"line_start": " * "`, I'll try `"allowed_line_starts": ["* ", "*\t"]`. It's a little more conservative (if less elegant) than `"line_start": "*"`.

**Comment by natlefiyr** [comment]
Sounds good, thanks for being proactive about this!
