### ISSUE TITLE
Stopped working with JSDoc comments

### ISSUE THREAD

**Issue by jwbth** [btrekkie/WrapAsYouType#9]
For unclear reasons, this suddenly stopped working with JSDoc comments (i.e. wrapping doesn't happen):
```
		{
			"line_start": " * ",
			"selector": "comment.block - punctuation.definition.comment"
		},
```
With regular block comments (started with `/*`, not `/**`), it continues to work.

I tried to play around and figured out that removing `.definition` helps. But I have no idea why and what the effect of `.definition` is supposed to be (reading the manual didn't help), hence whether the removal will break the workings of the plugin in any other place.

**Comment by jwbth** [comment]
> For unclear reasons, this suddenly stopped working with JSDoc comments (i.e. wrapping doesn't happen):
> 
> ```
> 		{
> 			"line_start": " * ",
> 			"selector": "comment.block - punctuation.definition.comment"
> 		},
> ```
> 
> With regular block comments (started with `/*`, not `/**`), it continues to work.
> 
> I tried to play around and figured out that removing `.definition` helps. But I have no idea why and what the effect of `.definition` is supposed to be (reading the manual didn't help), hence whether the removal will break the workings of the plugin in any other place.

**Comment by btrekkie** [comment]
Sorry, I'm not sure how I missed this issue. Sublime changed the scope semantics for JavaScript files. I've updated the recommended settings in the readme to work with the new scopes. Try using the following `"wrap_as_you_type_sections"` snippet instead:

```json
{
    "line_start": [" * "],
    "selector":
        "comment.block - (punctuation.definition.comment.begin | punctuation.definition.comment.end)"
},
```
